### ISSUE TITLE
Tracking: Backport upstream network encapsulation

### ISSUE THREAD

**Issue by PRCYDev** [PRCYCoin/PRCYCoin#4]
This is to track the backporting of various upstream PRs leading up to the goal of the P2P network encapsulation:
 
* [ ]  [bitcoin#7868](https://github.com/bitcoin/bitcoin/pull/7868)
* [ ]  [bitcoin#7350](https://github.com/bitcoin/bitcoin/pull/7350)
* [ ]  [bitcoin#6780](https://github.com/bitcoin/bitcoin/pull/6780)
* [ ]  [bitcoin#7257](https://github.com/bitcoin/bitcoin/pull/7257)
* [ ]  [bitcoin#7696](https://github.com/bitcoin/bitcoin/pull/7696)
* [ ]  [bitcoin#8083](https://github.com/bitcoin/bitcoin/pull/8083)
* [ ]  [bitcoin#8065](https://github.com/bitcoin/bitcoin/pull/8065)
* [ ]  [bitcoin#7181](https://github.com/bitcoin/bitcoin/pull/7181)
* [ ]  [bitcoin#6059](https://github.com/bitcoin/bitcoin/pull/6059)
* [ ]  [bitcoin#7749](https://github.com/bitcoin/bitcoin/pull/7749)
* [ ]  [bitcoin#8208](https://github.com/bitcoin/bitcoin/pull/8208)
* [ ]  [bitcoin#6556](https://github.com/bitcoin/bitcoin/pull/6556)
* [ ]  [bitcoin#8113](https://github.com/bitcoin/bitcoin/pull/8113)
* [ ]  [bitcoin#8128](https://github.com/bitcoin/bitcoin/pull/8128)
* [ ]  [bitcoin#8282](https://github.com/bitcoin/bitcoin/pull/8282)
* [ ]  [bitcoin#8466](https://github.com/bitcoin/bitcoin/pull/8466)
* [ ]  [bitcoin#8606](https://github.com/bitcoin/bitcoin/pull/8606)
* [ ]  [bitcoin#8085](https://github.com/bitcoin/bitcoin/pull/8085)
* [ ]  [bitcoin#9289](https://github.com/bitcoin/bitcoin/pull/9289)
* [ ]  [bitcoin#8740](https://github.com/bitcoin/bitcoin/pull/8740)
* [ ]  [bitcoin#8661](https://github.com/bitcoin/bitcoin/pull/8661)

(following similar path to https://github.com/PIVX-Project/PIVX/issues/1374)
